# Generated by Django 3.2.13 on 2022-06-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0004_alter_reservation_number_of_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='first_name',
            new_name='reservation_under',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='last_name',
        ),
    ]
