# Generated by Django 3.2.13 on 2022-06-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0005_auto_20220626_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='date_of_reservation',
        ),
    ]
