# Generated by Django 3.2.13 on 2022-06-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0006_rename_date_reservation_date_of_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(choices=[('12:00', '12:00'), ('14:00', '14:00'), ('17:00', '17:00'), ('19:00', '19:00'), ('21:00', '21:00')], default='19:00', max_length=5),
        ),
    ]
