# Generated by Django 3.2.13 on 2022-06-27 15:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0007_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_of_reservation',
            field=models.DateField(unique=True, validators=[django.core.validators.MinValueValidator(datetime.date(2022, 6, 28))]),
        ),
    ]
